from django.urls import path, include
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    path('addproducttofavorite/<int:product_id>', views.add_product_to_favorite, name='add_product_to_favorite'),
    path('deleteproductfromfavorite/<int:product_id>', views.delete_product_from_favorite, name='delete_product_from_favorite'),
    path('adddishtofavorite/<int:dish_id>', views.add_dish_to_favorite, name='add_dish_to_favorite'),
    path('deletedishfromfavorite/<int:dish_id>', views.delete_product_from_favorite, name='delete_dish_from_favorite'),
    url(r'^products/$', views.ProductListView.as_view(), name='products'),
    url(r'^prices/$', views.PriceListView.as_view(), name='prices'),
    url(r'^dishes/$', views.DishListView.as_view(), name='dishes'),
    url(r'^kitchen-utensils/$', views.KitchenUtensilListView.as_view(), name='kitchen_utensils'),
    url(r'^kitchen-utensil/(?P<pk>\d+)$', views.KitchenUtensilDetailView.as_view(), name='kitchen_utensil_detail'),
    url(r'^dish/(?P<pk>\d+)$', views.DishDetailView.as_view(), name='dish-detail'),
    url(r'^product/(?P<pk>\d+)$', views.ProductDetailView.as_view(), name='product-detail'),
    url(r'^stores/$', views.StoreListView.as_view(), name='stores'),
    url(r'^store/(?P<pk>\d+)$', views.StoreDetailView.as_view(), name='store-detail'),
    url(r'^my-products/$', views.UsersProductsListView.as_view(), name='my-products'),
    url(r'^my-stores/$', views.UsersStoresListView.as_view(), name='my-stores'),
    url(r'^my-prices/$', views.UsersPricesListView.as_view(), name='my-prices'),
    url(r'^my-dishes/$', views.UsersDishesListView.as_view(), name='my-dishes'),
    url(r'^my-kitchen-utensils/$', views.UsersKitchenUtensilsListView.as_view(), name='my-kitchen-utensils'),
    url(r'^my-favorite-products/$', views.UsersFavoriteProductsListView.as_view(), name='my-favorite-products'),
    url(r'^my-favorite-dishes/$', views.UsersFavoriteDishesListView.as_view(), name='my-favorite-dishes'),
    url(r'^product/(?P<pk>[-\w]+)/renew-product/$', views.renew_product, name='renew-product'),
    url(r'^store/(?P<pk>[-\w]+)/renew-store/$', views.renew_store, name='renew-store'),
    url(r'^price/(?P<pk>[-\w]+)/renew-price/$', views.renew_price, name='renew-price'),
    url(r'^kitchen-utensil/(?P<pk>[-\w]+)/renew-kitchen-utensil/$', views.renew_kitchen_utensil, name='renew-kitchen-utensil'),
    url(r'^dish/(?P<pk>[-\w]+)/renew-dish/$', views.renew_dish, name='renew-dish'),
    url(r'^product/create/$', views.ProductCreate.as_view(), name='product_create'),
    url(r'^product/(?P<pk>\d+)/delete/$', views.ProductDelete.as_view(), name='product_delete'),
    url(r'^store/create/$', views.StoreCreate.as_view(), name='store_create'),
    url(r'^store/(?P<pk>\d+)/delete/$', views.StoreDelete.as_view(), name='store_delete'),
    url(r'^dish/(?P<pk>\d+)/delete/$', views.DishDelete.as_view(), name='dish_delete'),
    url(r'^kitchen-utensil/(?P<pk>\d+)/delete/$', views.KitchenUtensilDelete.as_view(), name='kitchen_utensil_delete'),
    url(r'^price/create/$', views.PriceCreate.as_view(), name='price_create'),
    url(r'^dish/create/$', views.create_dish, name='dish_create'),
    url(r'^kitchen-utensil/create/$', views.KitchenUtensilCreate.as_view(), name='kitchen_utensil_create'),
    url(r'^kitchen-utensil/(?P<pk>\d+)/delete/$', views.KitchenUtensilDelete.as_view(), name='kitchen_utensil_delete'),
    url(r'^price/(?P<pk>\d+)/delete/$', views.PriceDelete.as_view(), name='price_delete'),
]
