# Generated by Django 3.2 on 2021-06-01 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_alter_product_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='who_added',
            field=models.ManyToManyField(related_name='who_added_to_price_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='who_added',
            field=models.ManyToManyField(related_name='who_added_to_product_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='who_added',
            field=models.ManyToManyField(related_name='who_added_to_store_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
