# Generated by Django 3.2 on 2021-06-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210601_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='who_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='who_added',
        ),
        migrations.RemoveField(
            model_name='store',
            name='who_added',
        ),
    ]
