# Generated by Django 3.2 on 2021-06-11 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210603_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenUtensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter kitchen utensil name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('k', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('m', 'Milliliter')], default='k', help_text='Choose unit', max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter dish name', max_length=200)),
                ('recipe', models.CharField(help_text='Enter recipe', max_length=1000)),
                ('kitchen_utensils', models.ManyToManyField(to='catalog.KitchenUtensil')),
                ('products', models.ManyToManyField(to='catalog.ProductAmount')),
            ],
        ),
    ]
