# Generated by Django 3.2 on 2021-06-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_dish_kitchenutensil_productamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.CharField(help_text='Enter recipe', max_length=10000),
        ),
    ]
