# Generated by Django 3.2 on 2021-06-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_dish_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productamount',
            name='unit',
            field=models.CharField(choices=[('k', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('m', 'Milliliter'), ('t', 'Thing')], default='k', help_text='Choose unit', max_length=1),
        ),
    ]
