# Generated by Django 3.2 on 2021-06-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_productamount_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productamount',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('thing', 'Thing')], default='k', help_text='Choose unit', max_length=10),
        ),
    ]
