# Generated by Django 3.2 on 2021-06-28 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0013_alter_productamount_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='who_added',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_added_to_dish_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kitchenutensil',
            name='who_added',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_added_to_kitchen_utensil_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
