# Generated by Django 3.2 on 2021-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210628_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.ProductAmount'),
        ),
    ]
