# Generated by Django 3.2 on 2021-07-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_dish_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productamount',
            name='related_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.dish'),
            preserve_default=False,
        ),
    ]
