# Generated by Django 3.2 on 2021-07-08 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0020_auto_20210704_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_dish_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_product_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
