# Generated by Django 3.2.5 on 2021-07-24 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0022_auto_20210714_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('weight', models.FloatField()),
                ('nursing', models.BooleanField(blank=True, null=True)),
                ('kid_date_of_birth', models.DateField(blank=True, null=True)),
                ('cpa', models.CharField(choices=[('i', 'workers mostly mental work, very light physical activity'), ('ii', 'workers engaged in light work, light physical activity'), ('iii', 'workers of average hard work, average physical activity'), ('iv', 'workers of hard physical labor, high physical activity'), ('v', 'workers of especially heavy physical work, very high physical activity')], default='i', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
