# Generated by Django 3.2.5 on 2021-07-26 07:18

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20210726_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
